#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

print_info () {
    domain="$1"
    subdomain="$2"
    fullsubdom="${subdomain}.${domain}" 
    ip=$(dig "${fullsubdom}" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n' )
    #p=$(dig "${fullsubdom}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -1)
    rectype=$(dig "${fullsubdom}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | head -1)
    echo "The subdomain $subdomain is a $rectype record and points to $ip"

}

if [ "$#" -eq 2 ]; then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "lb-01"
    print_info "web-01.$1" "web-01"
    print_info "web-02.$1" "web-02"
fi
