#!/usr/bin/env bash
# Install nginx web server

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Allow HTTP traffic through the firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Start Nginx
sudo service nginx start
