#!/usr/bin/env bash
# Install nginx web server

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Allow HTTP traffic through the firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Start Nginx
sudo /usr/sbin/nginx
