#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo '<h1>Hello World!</h1>' > /var/www/html/index.html
sudo service nginx restart
