#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install nginx -y
sudo echo "<h1>Hello World!</h1>" >> /var/www/html/index.html

sudo service nginx restart
