#!/usr/bin/env bash
# error page with a massage
sudo echo "<h1>Ceci n'est pas une page</h1>" | sudo tee -a /var/www/html/custom_error.html

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo service nginx start


old_line="server_name _;"
new_line="server_name foash.tech;\n        location /redirect_me { \n       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }\n        error_page 404 /custom_error.html;\n"

sudo sed -i "s|${old_line}|${new_line}|g" /etc/nginx/sites-enabled/default 

sudo service nginx restart
service nginx reload
# #!/usr/bin/env bash
# # a Bash script containing commands to automatically configure a Ubuntu machine so that /redirect_me is redirecting to another page  “301 Moved Permanently”
# sudo apt-get -y update
# sudo apt-get -y install nginx
# sudo ufw allow 'Nginx HTTP'
# echo "Hello World!" | sudo tee /var/www/html/index.html
# echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
# sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.linkedin.com/in/aya-anwar-473115279/;' /etc/nginx/sites-available/default
# sudo sed -i "/redirect_me/ a\ error_page 404 /404.html;" /etc/nginx/sites-available/default
# sudo service nginx restart
# service nginx reload
