#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu machine so that /redirect_me is redirecting to another page  “301 Moved Permanently”
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.linkedin.com/in/aya-anwar-473115279/;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me/ a\\\terror_page 404 /404.html; /etc/nginx/sites-available/default
sudo service nginx restart
