#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu machine so that /redirect_me is redirecting to another page “301 Moved Permanently”
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R www-data:www-data /var/www/html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.linkedin.com/in/aya-anwar-473115279/ permanent;' /etc/nginx/sites-available/default
sudo sed -i "/redirect_me/ a\\\t error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
