#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt update -y
sudo apt install haproxy -y
printf '%s\n' "
frontend http
    bind 0.0.0.0:80
    default_backend http_servers" >> /etc/haproxy/haproxy.cfg

printf '%s\n' "
backend http_servers
    balance roundrobin
    server 433678-web-01 54.208.42.72:80 check
    server 433678-web-02 54.208.90.100:80 check" >> /etc/haproxy/haproxy.cfg


sudo systemctl enable haproxy
sudo service haproxy restart
