#!/usr/bin/env bash
#the script that displays Best School 10 times.
num=1
while ((num <= 11))
do
    if ((num == 10))
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((num++))
done
