#!/usr/bin/env bash
# the script that displays Best School 10 times.
num=1
while ((num <= 20))
do
    if ((num == 4))
    then
        echo "bad luck from China"
    elif ((num == 9))
    then
        echo "bad luck from Japan"
    elif ((num == 17))
    then
        echo "bad luck from Italy"
    else
        echo "$num"
    fi
    ((num++))
done
