#!/usr/bin/env bash
# Backup the original hosts file
cp /etc/hosts ~/host.new
# Modify the hosts file
sed -i 's/127.0.0.1/127.0.0.2/' ~/host.new
sed -f '2i8.8.8.8 facebook.com' ~/host.new
# Copy the modified "hosts.new" file to the system's "/etc/hosts" file, overwriting its contents
cp ~/host.new /etc/hosts
